### ISSUE TITLE
Error in Multiple Instances

### ISSUE THREAD

**Issue by niketkdoshi** [goraft/raftd#21]
Hi,
 I am not able to start the multiple instances i.e nodes which will follow the leader.
Please help or you can post video of how you are instantiating multiple servers so that we can also do the same.

Error : 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xb0 pc=0x4a7962]

goroutine 1 [running]:
github.com/goraft/raftd/server.(*Server).Join(0xc820082080, 0x86d2e0, 0x15, 0x0, 0x0)
    /~/newraft/src/github.com/goraft/raftd/server/server.go:132 +0x62
main.main()
    ~/newraft/src/github.com/goraft/node/raftd/main.go:66 +0x5e8

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
exit status 2
```

**Comment by philips** [comment]
Sorry, this project is unmaintained: https://github.com/goraft/raftd#raftd

**Comment by niketkdoshi** [comment]
Hi,
I can run multiple instances of the nodes and it works fine.
But the only issue is automatic leader selection fails if I have only 1 leader & 1 follower and leader fails then follower is not being the leader until an unless any other client joins the network

**Comment by philips** [comment]
I get what you are saying. But, I am just trying to set expecations that no one is going to fix this bug nor help you.
